### ISSUE TITLE
Login state is not retained

### ISSUE THREAD

**Issue by dg01d** [EdwardHinkle/indigenous-ios#21] opened 2017-11-10 10:56 UTC
Hi Eddie,

I open Indigenuous, get the login screen. I enter the site address, https://ascraeus.org/, and get the redirect to IndieAuth, that's all fine.

After logging into a designated provider, the program exits. On relaunch, the screen briefly flashes logged in as - then resets to the login screen.

iOS 11, iPhone 6

**Comment by EdwardHinkle** [comment] 2017-11-10 21:39
Thanks for letting me know!

This is likely a duplicate of #23 so I'll close this for now :)

**Closed by EdwardHinkle** 2017-11-10 21:39 UTC
Labels: duplicate
